# Generated by Django 2.2.3 on 2019-07-07 19:01

from django.db import migrations
import jobsapp.managers


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', jobsapp.managers.UserManager()),
            ],
        ),
    ]
