# Generated by Django 2.2.3 on 2019-07-07 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0004_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
