# Generated by Django 2.2.3 on 2019-07-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0005_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
