# Generated by Django 2.2.2 on 2019-07-08 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0008_employeedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employeeDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirer', to='jobsapp.EmployeeDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.User')),
            ],
        ),
    ]
