# Generated by Django 2.2.2 on 2019-07-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skillRequired1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='skillRequired2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_experience',
            field=models.IntegerField(default=0),
        ),
    ]
