# Generated by Django 2.2.2 on 2019-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_auto_20190710_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='CVs/'),
        ),
    ]
