# Generated by Django 2.2.2 on 2019-07-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0011_auto_20190710_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
