# Generated by Django 2.2.2 on 2019-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0012_auto_20190714_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='employeeProfile'),
        ),
    ]
